import sys
import re
import os

todo_file = sys.argv[1]

mapping = {
    "0f46603": "chore: update gitignore",
    "8bd25b6": "feat: implement maintenance mode",
    "4f054c5": "fix: update WordSearchGame logic",
    "2c76761": "fix: update ScoringCriteria and api service",
    "e9ee18a": "fix: minor updates to MatchTheWord and WordSearch games",
    "da536eb": "feat: update scoring criteria and API routes",
    "d341f99": "fix: update API routes",
    "6bb474b": "feat: add new API routes",
    "2828ba7": "fix: update VerseScrambleGame",
    "120b744": "fix: update VerseScrambleGame logic",
    "7d5150a": "refactor: update DarkModeCrossword component",
    "6d350ee": "fix: update ConnectionsGame",
    "e87ab2d": "fix: minor API route update",
    "4bdd269": "feat: add touch support to WordSearchGame",
    "17473db": "feat: update GameBuilder and API for WordSearch",
    "d0872e4": "fix: update AdminDashboard and MatchTheWordGame",
    "c8e1bf4": "feat: update GameBuilder and API for MatchTheWord",
    "3b39e22": "feat: support multiple verses in GameBuilder",
    "8865dad": "feat: support multiple crosswords in GameBuilder",
    "1b9eb88": "feat: support multiple connections games in GameBuilder",
    "64855d0": "feat: support multiple solutions in Hangman",
    "1b7bbee": "fix: update API routes",
    "0614b09": "feat: add banner message component",
    "bb63c02": "fix: update API routes",
    "753fc82": "fix: update API routes",
    "22b635b": "fix: update API routes",
    "097cae7": "fix: update API routes",
    "22c1d8e": "fix: update API routes",
    "516f442": "fix: update API routes",
    "9389293": "fix: update API routes",
    "54eae11": "fix: update API routes",
    "3d1c3d1": "feat: add advanced Wordle mode",
    "922f0f8": "fix: resolve merge conflicts",
    "98c9161": "fix: update API routes",
    "0447e61": "fix: update API routes",
    "4932070": "fix: update API routes",
    "cf86ed2": "fix: update API routes",
    "d341123": "fix: miscellaneous updates",
    "901e906": "fix: resolve issues",
    "b50c433": "fix: update API routes",
    "5128717": "fix: update API routes",
    "d45092e": "fix: update API routes",
    "a4bc91e": "fix: update API routes",
    "7641091": "fix: update API routes",
    "ccf8268": "fix: update API routes",
    "732c5f7": "fix: update API routes",
    "3aa99e5": "feat: add notification system",
    "bfd0ae4": "fix: update API routes",
    "a33eca3": "fix: update API routes",
    "2632e6d": "fix: update API routes",
    "3a2feda": "fix: update API routes",
    "b2e6933": "fix: update API routes",
    "6daa1c2": "fix: update API routes",
    "296460f": "fix: update API routes",
    "d1359d4": "fix: update API routes",
    "439aace": "fix: update API routes",
    "421c4cf": "fix: update API routes",
    "80fbd5a": "fix: update API routes",
    "88f3c37": "feat: add daily message feature",
    "ce04681": "fix: update API routes",
    "f802e2a": "fix: update API routes",
    "ab108ed": "fix: update API routes",
    "8c5179f": "fix: update API routes",
    "8caa0c6": "fix: update API routes",
    "79b0223": "fix: update API routes",
    "417ed59": "fix: update API routes",
    "5faf4a3": "fix: update API routes",
    "35fb5e3": "fix: update API routes",
    "6f69ff5": "fix: update API routes",
    "02032d4": "chore: check code status",
    "2289718": "fix: update API routes",
    "c8c3bed": "fix: update API routes",
    "e11d9a4": "fix: update API routes",
    "86c95e3": "fix: update API routes",
    "3c2865f": "fix: update API routes",
    "5c59a1c": "fix: update API routes",
    "0f61983": "fix: update API routes",
    "5f22999": "fix: miscellaneous updates",
    "4e825ec": "fix: update API routes",
    "26baefd": "fix: update API routes",
    "50ae90e": "fix: update API routes",
    "0afcd84": "feat: update SMYM app",
    "812e3f0": "feat: add links to SMYM Bible app",
    "5bc158e": "fix: upgrade dependencies",
    "46924f7": "fix: update API routes",
    "f0c4c25": "fix: update API routes",
    "6122de1": "fix: update API routes",
    "c4c89ec": "fix: miscellaneous updates",
    "e645bbd": "fix: miscellaneous updates",
    "2431cfb": "fix: update API routes",
    "4c0bf9b": "fix: update API routes",
    "e8c1fdb": "fix: update API routes",
    "b86fd3f": "fix: update API routes",
    "72e131b": "fix: miscellaneous updates",
    "4baafcb": "fix: miscellaneous updates",
    "77fe728": "fix: update API routes",
    "6750f8d": "fix: update API routes",
    "74f7718": "feat: add privacy policy",
    "7fc7258": "fix: miscellaneous updates",
    "c4cd89a": "fix: update API routes",
    "bb38a61": "fix: update API routes",
    "13fc6cf": "fix: update API routes",
    "aa427e2": "fix: update API routes",
    "10c3ae8": "fix: update API routes",
    "6a987f9": "fix: update API routes",
    "9493ff5": "fix: update API routes",
    "dd894d8": "fix: update API routes",
    "1a39a42": "fix: update API routes",
    "747a792": "fix: miscellaneous updates",
    "1123f04": "fix: update API routes",
    "1aad883": "fix: resolve issues",
    "e52bc50": "fix: miscellaneous updates",
    "e25f58f": "chore: test push",
    "562cb6c": "fix: update API routes",
    "40c00c8": "fix: update API routes",
    "84d249c": "feat: update app components",
    "6b18ad1": "fix: update API routes",
    "35953f3": "fix: update API routes",
    "1e24608": "fix: update API routes",
    "beedc1d": "fix: update API routes",
    "bf8a0d0": "fix: update API routes",
    "c0d413f": "fix: miscellaneous updates",
    "ec4c639": "fix: miscellaneous updates",
    "3c11dba": "fix: miscellaneous updates",
    "8cc3ab8": "fix: update API routes",
    "ee91e50": "fix: update API routes",
    "65b6cc5": "fix: update API routes",
    "9bf669d": "fix: miscellaneous updates",
    "9757e9f": "fix: update API routes",
    "288ae99": "fix: update API routes",
    "34b0646": "fix: update API routes",
    "490fcf2": "feat: add crossword game",
    "4c237c1": "fix: update API routes",
    "334b7b7": "fix: update API routes",
    "80dd61b": "fix: resolve issues",
    "dd1f337": "fix: resolve issues",
    "8518af9": "fix: update API routes",
    "6ffbbe2": "fix: update API routes",
    "c443356": "fix: update API routes",
    "33c6062": "fix: update API routes",
    "91017ec": "fix: resolve issues",
    "d59ee1b": "feat: add admin dashboard",
    "982c600": "fix: update API routes",
    "efad1fc": "fix: update API routes",
    "2849111": "fix: miscellaneous updates",
    "ef5a20d": "fix: update API routes",
    "c41356e": "fix: update API routes",
    "0b2a7a2": "feat: add reset password functionality",
    "ff23b8a": "fix: miscellaneous updates",
    "2367ca4": "feat: handle app url deep linking",
    "0fe7360": "fix: update API routes",
    "59b9ed3": "feat: add to home screen prompt",
    "38ba7f0": "fix: update push notifications hook",
    "5e1093e": "fix: update scheduler",
    "8bb3050": "feat: add logger middleware",
    "e066910": "chore: update docker-compose",
    "be04859": "fix: update server configuration",
    "a83dbf0": "fix: update server configuration",
    "63977f4": "fix: update rate limiting",
    "1a05b71": "feat: add service worker",
    "27470bd": "fix: update push notifications and API",
    "4629f55": "fix: update scheduler logic",
    "160f3a6": "feat: add push notification service and components",
    "c448854": "feat: add email service and auth modal updates",
    "c8012ea": "fix: update API routes for all games",
    "3b03e6f": "fix: update seed data",
    "ca5a1bc": "feat: major update to game components and API",
    "c6cc040": "fix: update seed data and scoring",
    "c67fbc2": "feat: major update to auth and game logic",
    "af4acce": "feat: add new game features",
    "064fe82": "feat: add DarkModeCrossword and update games",
    "d9bfa8f": "Merge pull request #2 from isaacdomini/copilot/update-app-to-run-on-server",
    "0a28160": "chore: add TODO for password hashing",
    "891b722": "docs: update documentation",
    "0c7bb65": "feat: add rate limiting and fix seed data",
    "5827641": "fix: vite port and docker config",
    "b05cc91": "feat: add backend server and docker setup",
    "ca50f6d": "chore: initial commit - server setup",
    "ba2b752": "docs: initial plan",
    "64737c0": "feat: initialize project",
    "347faff": "chore: initial commit",
    "2d365b8": "fix: update auth middleware and API routes",
    "cb60cf9": "fix: update game components",
    "8c45f3c": "fix: update API routes",
    "6f69956": "fix: remove unused code from api service",
    "7974e24": "chore: clean up test files and update ChallengeHistory",
    "84c178a": "test: add game state privacy verification script",
    "39223ff": "test: add integration tests and verify curl user",
    "02b2ed6": "feat: add dev tools detection and comprehensive integration tests",
    "529fb60": "feat: implement JWT authentication"
}

print(f"Processing {todo_file}")

with open(todo_file, 'r') as f:
    lines = f.readlines()

new_lines = []
for line in lines:
    new_lines.append(line)
    # Match "pick <hash>" or "merge -C <hash>"
    match = re.search(r'^(?:pick|merge -C)\s+([0-9a-f]+)', line)
    if match:
        short_hash = match.group(1)
        # Check for match
        for k, v in mapping.items():
            if short_hash.startswith(k) or k.startswith(short_hash):
                new_lines.append(f'exec git commit --amend -m "{v}"\n')
                break

with open(todo_file, 'w') as f:
    f.writelines(new_lines)
